Api call implemented
Faka-GLB/Marvel-mvvm pull request #3
Opened 2021-08-31 14:37 UTC by Faka-GLB

Api call using retrofit implemented, along with the response classes and a mapper to domain classes.
Also used LiveData and coroutines to display the result.
Dependencies injection implemented using koin v3.

Nexus 5X

2021-08-31 15:01 UTC, SartiMau requested changes

2021-08-31 15:01 UTC, SartiMau commented on domain/src/main/java/com/onboarding/domain/usecase/GetAllCharactersUseCase.kt
> +interface GetAllCharactersUseCase {
for code clarity pls put the interface first

2021-08-31 15:05 UTC, BQuinteros requested changes

2021-08-31 15:05 UTC, BQuinteros commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        attachObserver()
pls do not do this, we can do a better form to observe the live data

2021-08-31 16:45 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/utils/Data.kt
> +data class Data<RequestData>(var responseType: Status, var data: RequestData? = null, var error: Exception? = null)
done

2021-08-31 16:45 UTC, Faka-GLB commented on data/src/main/java/com/onboarding/data/mapper/MarvelMapper.kt
> +fun BaseResponse.transform() = Base(
privatized all methods except for BaseResponse.transform()

2021-08-31 16:46 UTC, Faka-GLB commented on data/src/main/java/com/onboarding/data/service/MarvelRequestGenerator.kt
> +
removed

2021-08-31 16:46 UTC, Faka-GLB commented on domain/src/main/java/com/onboarding/domain/usecase/GetAllCharactersUseCase.kt
> +interface GetAllCharactersUseCase {
done

2021-08-31 16:46 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        attachObserver()
done

2021-08-31 17:16 UTC, mauroLonghi commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +    private var _characters: MutableLiveData<Event<Data<MarvelData>>> = MutableLiveData()
"_character" not follow the right namely of variable, maybe you could remove "_" and add the suffix "liveData"

2021-08-31 17:17 UTC, mauroLonghi commented on data/src/main/java/com/onboarding/data/mapper/MarvelMapper.kt
> +@JvmName("transformItemResponse")
what is the propose of this annotation?

2021-08-31 17:22 UTC, mauroLonghi commented on domain/src/main/java/com/onboarding/domain/usecase/MarvelServiceUseCase.kt
> +interface MarvelServiceUseCase {
pls rename because it not be cleared if it is a Service or a Usecase , suggestion   MarvelRepository

2021-08-31 17:25 UTC, mauroLonghi commented on di/src/main/java/com/onboarding/di/koinModules.kt
> +    single<MarvelServiceUseCase> { MarvelServiceImpl() }
this it not right, the repository should be in his own module, not in the usecase module

2021-08-31 17:36 UTC, Faka-GLB commented on data/src/main/java/com/onboarding/data/mapper/MarvelMapper.kt
> +@JvmName("transformItemResponse")
it assign a name for the JVM compiler to put in that method's name, I use this to maintain the transform() name since I transform a List three times with different content classes.

2021-08-31 17:50 UTC, Faka-GLB commented on di/src/main/java/com/onboarding/di/koinModules.kt
> +    single<MarvelServiceUseCase> { MarvelServiceImpl() }
moved to its own module

2021-08-31 17:50 UTC, Faka-GLB commented on domain/src/main/java/com/onboarding/domain/usecase/MarvelServiceUseCase.kt
> +interface MarvelServiceUseCase {
renamed to MarvelRepository

2021-08-31 17:50 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +    private var _characters: MutableLiveData<Event<Data<MarvelData>>> = MutableLiveData()
done

2021-08-31 18:42 UTC, mauroLonghi commented on data/src/main/java/com/onboarding/data/service/MarvelServiceImpl.kt
> +class MarvelServiceImpl : MarvelRepository {
if you rename the Contract, you should renamed the implementation. Suggestion : MarvelRepositoryImpl

2021-08-31 18:52 UTC, Faka-GLB commented on data/src/main/java/com/onboarding/data/service/MarvelServiceImpl.kt
> +class MarvelServiceImpl : MarvelRepository {
wops, renamed

2021-08-31 18:58 UTC, SartiMau requested changes

2021-08-31 18:58 UTC, SartiMau commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +            Status.SUCCESSFUL -> {
you should show something on the LOADING state and the ERROR state here

2021-08-31 18:58 UTC, SartiMau commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +        mutableLiveDataCharacters.value = Event(Data(responseType = Status.LOADING))
on this case the UI show nothing

2021-08-31 18:58 UTC, SartiMau commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +                mutableLiveDataCharacters.value = Event(Data(responseType = Status.ERROR, error = result.exception))
on this case the UI show nothing

2021-08-31 18:59 UTC, nicolbidone requested changes

2021-08-31 18:59 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +    private fun updateUI(state: Event<Data<MarvelData>>?) {
instead of a function here you can set an observer by variable as
private val updateUIObserver = Observer<Event<Data<MarvelData>>> { ... }

2021-08-31 18:59 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        when (state?.peekContent()?.responseType) {
wrong, if you're using a live data event you should invoke getContentIfNotHandled, if you force it is useless

2021-08-31 18:59 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +        get() = mutableLiveDataCharacters
why two live data for the same thing?

2021-08-31 18:59 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +data class Data<RequestData>(var responseType: Status, var data: RequestData? = null, var error: Exception? = null)
this should be o a separate file

2021-08-31 18:59 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +enum class Status { SUCCESSFUL, ERROR, LOADING }
this should be on a separate file

2021-08-31 18:59 UTC, nicolbidone commented on data/src/main/java/com/onboarding/data/service/api/MarvelApi.kt
> +        @Query("ts") ts: Int,
variable names doesn't need to be equal to the query id, please use descriptive names

2021-08-31 18:59 UTC, nicolbidone commented on domain/src/main/java/com/onboarding/domain/entity/CollectionItem.kt
> +    val type: String?
Does this need to be nullable? can be empty?

2021-08-31 19:04 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +enum class Status { SUCCESSFUL, ERROR, LOADING }
It was, Mauro told me to leave it in the viewmodel class

2021-08-31 19:05 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +data class Data<RequestData>(var responseType: Status, var data: RequestData? = null, var error: Exception? = null)
It was, Mauro told me to leave it in the viewmodel class

2021-08-31 19:08 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +        get() = mutableLiveDataCharacters
if the mutable is public, it breaks encapsulation, this is the way the LiveData readings used to provide access to the data

2021-09-01 13:30 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +            Status.SUCCESSFUL -> {
added a ProgressBar

2021-09-01 13:30 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +        mutableLiveDataCharacters.value = Event(Data(responseType = Status.LOADING))
addressed

2021-09-01 13:31 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +                mutableLiveDataCharacters.value = Event(Data(responseType = Status.ERROR, error = result.exception))
addressed

2021-09-01 13:31 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        when (state?.peekContent()?.responseType) {
done

2021-09-01 13:31 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +    private fun updateUI(state: Event<Data<MarvelData>>?) {
done

2021-09-01 13:32 UTC, Faka-GLB commented on data/src/main/java/com/onboarding/data/service/api/MarvelApi.kt
> +        @Query("ts") ts: Int,
renamed

2021-09-01 15:46 UTC, SartiMau requested changes

2021-09-01 15:46 UTC, SartiMau commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        private const val LENGTH_SHORT: Int = 0
remove these constants and use the Toast native actions Toast.LENGTH_LONG or Toast.LENGTH_SHORT

2021-09-01 17:57 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        private const val LENGTH_SHORT: Int = 0
done

2021-09-01 18:15 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +        get() = mutableLiveDataCharacters
so instead of creating a variable and not use it, why you don't do this as a function?

2021-09-01 18:24 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +        get() = mutableLiveDataCharacters
supposedly that was the norm, var removed and used a function instead

2021-09-01 18:29 UTC, mauroLonghi approved these changes

2021-09-01 18:35 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/viewmodel/MainViewModel.kt
> +data class Data<RequestData>(var responseType: Status, var data: RequestData? = null, var error: Exception? = null)
we agree to leave it like this 👍🏻

2021-09-01 18:50 UTC, nicolbidone approved these changes

2021-09-01 19:06 UTC, BQuinteros approved these changes

2021-09-01 19:35 UTC, merged