Implemented recycler view to show query results
Faka-GLB/Marvel-mvvm pull request #4
Opened 2021-09-02 15:33 UTC by Faka-GLB

Implemented a simple recycler view to show characters names obtained from the api response

Nexus 5X:
![image](https://user-images.githubusercontent.com/84337198/131869847-d4dee308-cc96-4e45-9753-4ba0f733a3b8.png)

Nexus S:
![image](https://user-images.githubusercontent.com/84337198/131869910-72e43e0e-24c8-409c-8cb7-d1d87a6a53a1.png)

Demo:
![characters_recycler](https://user-images.githubusercontent.com/84337198/131873110-54390a70-76dd-441a-8928-32af6cd5eda0.gif)

App module:
![image](https://user-images.githubusercontent.com/84337198/131870679-c4c1f424-810c-45e4-8961-814e02636f37.png)

Data module:
![image](https://user-images.githubusercontent.com/84337198/131870981-73017ad2-0c10-4d52-9db2-b9e4ef71464a.png)

Di and Domain modules:
![image](https://user-images.githubusercontent.com/84337198/131871666-960c5e33-4798-4e50-bbae-ba733a8cea1c.png)

Gradle scripts:
![image](https://user-images.githubusercontent.com/84337198/131871760-29f97b12-8724-4a64-8855-c8a4097f3157.png)

2021-09-02 15:39 UTC, SartiMau requested changes
Please use Glide to show the character image in each card pls

2021-09-02 18:56 UTC, BQuinteros approved these changes

2021-09-03 12:24 UTC, mauroLonghi commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        binding.textViewMainActivityTitle.visibility = View.GONE
I think that its better first hide the component and then set and put visible the recycler, to be consistent with the hive progress bar in the line 55

2021-09-03 12:25 UTC, mauroLonghi commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/text_view_main_activity_title"
pls remove "+" in the contranints

2021-09-03 12:26 UTC, mauroLonghi commented on app/src/main/res/layout/item_character.xml
> +                app:layout_constraintStart_toStartOf="parent"
if you are using match_parent, its not necesary this contraint

2021-09-03 14:01 UTC, Faka-GLB commented on app/src/main/res/layout/item_character.xml
> +                app:layout_constraintStart_toStartOf="parent"
removed

2021-09-03 14:05 UTC, Faka-GLB commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/text_view_main_activity_title"
removed

2021-09-03 14:05 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        binding.textViewMainActivityTitle.visibility = View.GONE
rearrenged lines

2021-09-03 14:10 UTC, SartiMau reviewed
Please add an EMPTY_LIST estate or something to show in case of the service response with an empty list

2021-09-03 14:50 UTC, SartiMau approved these changes

2021-09-03 14:54 UTC, BQuinteros approved these changes

2021-09-03 15:17 UTC, nicolbidone requested changes

2021-09-03 15:17 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        when (event?.peekContent()?.responseType) {
please don't force the read of the event

2021-09-03 15:17 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
>          binding.progressBarMainActivity.visibility = View.GONE
to show or hide multiple view at once you can try to use constraint layout groups

2021-09-03 15:17 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        binding.recyclerViewMainActivity.visibility = View.INVISIBLE
why do you make this invisible and not gone?

2021-09-03 15:17 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/adapter/CharacterAdapter.kt
> +        return ViewHolder(LayoutInflater.from(parent.context).inflate(R.layout.item_character, parent, false))
replace return for =

2021-09-03 15:17 UTC, nicolbidone commented on app/src/main/java/com/onboarding/marvel_mvvm/adapter/CharacterAdapter.kt
> +        return characterItems.size
replace return for =

2021-09-03 15:17 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="400dp"
please avoid hardcodes

2021-09-03 16:00 UTC, Faka-GLB commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="400dp"
avoided

2021-09-03 16:00 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/adapter/CharacterAdapter.kt
> +        return characterItems.size
done

2021-09-03 16:00 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/adapter/CharacterAdapter.kt
> +        return ViewHolder(LayoutInflater.from(parent.context).inflate(R.layout.item_character, parent, false))
done

2021-09-03 16:00 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        binding.recyclerViewMainActivity.visibility = View.INVISIBLE
replaced

2021-09-03 16:00 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
>          binding.progressBarMainActivity.visibility = View.GONE
done

2021-09-03 16:00 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
> +        when (event?.peekContent()?.responseType) {
done

2021-09-03 18:41 UTC, Faka-GLB commented on app/src/main/java/com/onboarding/marvel_mvvm/activity/MainActivity.kt
>          binding.progressBarMainActivity.visibility = View.GONE
redone

2021-09-03 19:36 UTC, nicolbidone approved these changes

2021-09-03 19:54 UTC, merged